# See https://bundler.io/gemfile.html
source "https://rubygems.org"
# frozen_string_literal: true

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'jekyll', '3.8.6'
gem 'just-the-docs', '0.2.7'
